# Site settings
title: 上海市青浦高级中学LG社
SEOTitle: LG社官网
header-img: img/post-bg-rwd.jpg
email: sya_123123@outlook.com
description: "永远的石楠花"
keyword: "青中，LG社"
url: "https://dsmtyu.github.io/"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/dsmtyu/dsmtyu.github.io.git" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "小撸怡情，大撸伤身，强撸灰飞烟灭"
sidebar-avatar: /img/about.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# SNS settings
RSS: false
# weibo_username:     none
# zhihu_username:    Dsmtyu
github_username:    Dsmtyu
# csdn_username:    Dsmtyu
# facebook_username:  none
# jianshu_username:   none
# twitter_username:   none




# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# 评论系统
# Disqus（https://disqus.com/）
# disqus_username: Dsmtyu

# Gitalk
gitalk:
  enable: true    #是否开启Gitalk评论
  clientID: 2467af9288ab06dd0f5e                            #生成的clientID
  clientSecret: 8a91ebac9fcad062293594a0d71596d4076b913a    #生成的clientSecret
  repo:  dsmtyu.github.io    #仓库名称
  owner: dsmtyu    #github用户名
  admin: dsmtyu
  distractionFreeMode: true #是否启用类似FB的阴影遮罩


# 统计

# Analytics settings
# Baidu Analytics
ba_track_id: b50bf2b12b5338a1845e33832976fd68

# Google Analytics
ga_track_id: 'UA-90855596-1'            # Format: UA-xxxxxx-xx
ga_domain: auto               # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto





# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 1              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
friends: [
    {
        title: "技术咨询",
        href: "https://github.com/qinpugaojizhongxuelgshe"
    }
]
