# Site settings
title: Albert Blog
SEOTitle: 吴宸宇的博客 | Albert-wuchenyu Blog
header-img: img/post-bg-rwd.jpg
email: 2845816276@qq.com
description: "认真你就输了！"
keyword: "Albert, Albert Blog, 吴宸宇的博客, Albert-wuchenyu, 吴宸宇"
url: "https://albert-wuchenyu.github.io/"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/Albert-wuchenyu/Albert-wuchenyu.github.io.git" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "When there's a will there's a way kind of beautiful."
sidebar-avatar: img/about.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# SNS settings
RSS: false
# weibo_username:     none
zhihu_username:    Dsmtyu
github_username:    Albert-wuchenyu
csdn_username:    </>.......</>
#facebook_username:  none
#jianshu_username:   none
#twitter_username:   none




# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# 评论系统
# Disqus（https://disqus.com/）
# disqus_username: Albert-wuchenyu

# Gitalk
gitalk:
  enable: true    #是否开启Gitalk评论
  clientID: Iv1.85a0ef5e8678659e                            #生成的clientID
  clientSecret: a3bb684528a5eb591208fc12c47427286f0a14ea    #生成的clientSecret
  repo:  Albert-wuchenyu.github.io    #仓库名称
  owner: Albert-wuchenyu    #github用户名
  admin: Albert-wuchenyu
  distractionFreeMode: true #是否启用类似FB的阴影遮罩


# 统计

# Analytics settings
# Baidu Analytics
ba_track_id: b50bf2b12b5338a1845e33832976fd68

# Google Analytics
ga_track_id: 'UA-90855596-1'            # Format: UA-xxxxxx-xx
ga_domain: auto               # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto





# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 1              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
friends: [
    {
        title: "CSDN",
        href: "https://blog.csdn.net/Albert_wuchenyu?spm=1000.2115.3001.5343"
    },{
        title: "博客园",
        href: "https://home.cnblogs.com/u/2735791"
    }
]
